import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "my-portfolio",
  description: "Generated by Henry Edet",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <h2>testing</h2>
      </head>
      <body className={inter.className}>
        <header>
          <h1>My Portfolio</h1>
          <nav>
            <a href="#about">About</a>
            <a href="#projects">Projects</a>
            <a href="#contact">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
