import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "my-portfolio",
  description: "Generated by Henry Edet",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>testing</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
